import contextvars

def inject() -> None: ...
def enable(debug: bool, sample_period: float = 1e-3, stack_minimum: float = 1e-3) -> None: ...
def finish() -> list[int]: ...
def cstack() -> list[contextvars.Context]: ...
