name: Build

on:
  push:

jobs:
  build_wheels:
    name: 'Wheels: ${{ matrix.os }}'
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-24.04
          - ubuntu-24.04-arm
          - macos-15-intel
          - macos-15

    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-python@v6
        with:
          python-version: '3.11'

      - name: Install cibuildwheel
        run: python -m pip install cibuildwheel==3.2.1

      - name: Build wheels
        run: python -m cibuildwheel --output-dir wheelhouse

      - uses: actions/upload-artifact@v4
        with:
          name: wheels-${{ matrix.os }}
          path: ./wheelhouse/*.whl

  group_wheels:
    name: 'Wheels: aggregate'
    runs-on: ubuntu-latest
    needs: build_wheels
    permissions:
      contents: write

    steps:
      - uses: actions/download-artifact@v4
        with:
          merge-multiple: true
          path: ./wheelhouse

      - uses: softprops/action-gh-release@v2
        with:
          tag_name: builds/${{ github.ref_name }}
          target_commitish: ${{ github.sha }}
          prerelease: true
          files: ./wheelhouse/*.whl
